Replaced std::copysign(x) with (x > 0 ? 1 : -1)
Summary:
Replaced std::copysign(x) with (x > 0 ? 1 : -1).
std::copysign is not available on some Android platforms which was detected in GitHub's Travis tests:
"/home/travis/build/caffe2/caffe2/caffe2/sgd/yellowfin_op.cc:57:23: error: 'copysign' is not a member of 'std'"

Reviewed By: akyrola

Differential Revision: D5756384

fbshipit-source-id: 56bc220d2c6216ff45b9cc47ed02aebf6ad439a5