Remove unbalanced `pragma diagnostic pop` (#83095)
Detected by internal CI, we should have it in OSS as well:
```
aten/src/ATen/native/cpu/Loops.h:398:24: error: pragma diagnostic pop could not pop, no matching push [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic pop
```
Regression introduced by https://github.com/pytorch/pytorch/pull/82883

Pull Request resolved: https://github.com/pytorch/pytorch/pull/83095
Approved by: https://github.com/albanD, https://github.com/seemethere