Wextra fix for LossCTC.cpp (#66381)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/66381

Fixes
```
stderr: caffe2/aten/src/ATen/native/cudnn/LossCTC.cpp:83:37: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'const long' [-Werror,-Wsign-compare]
  TORCH_CHECK(input_lengths_.size() == batch_size, "input_lengths needs to have size to match batch_size");
              ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
```

Test Plan: Sandcastle

Reviewed By: ngimel

Differential Revision: D31510217

fbshipit-source-id: e3585e08650950c08d80d347dfae375aedf2ceaf