Revert "[PyTorch] Improve aarch64 performance of bfloat16 ops (#166028)"
This reverts commit 3e77a2b478f596a8a0aef0af502f6bb1a247aa85.

Otherwise it fails ARM build with older compilers with errors that looks
as follows:
```
vec128_bfloat16_neon.h:666:12: error: operation not permitted on type ‘bfloat16_t’
  666 |   return (-x) * y - z;
```

For more self-contained example see https://godbolt.org/z/bbY4xWh45
(that compiles the same code using clang-15 and clang-19)