Ensure the minimum NVIDIA driver version to be 515.57 for CUDA 11.7 (#86344)
This does 2 things:

* Ensure that `nvidia-driver-latest-dkms` package is removed if it's installed. This allows the installation to go forward without the below error when using the standard installation script from S3:

```
(Answer: Abort installation)
ERROR: The installation was canceled due to the availability or presence of an alternate driver installation. Please see /var/log/nvidia-installer.log for more details.
```

* Not skipping the installation if a driver different than `515.57` exists to avoid any unexpected behavior when using a different driver version. This partly addresses the recent issue in https://github.com/pytorch/pytorch/issues/85778 in which `510.60.02` is there instead (not sure from where) and fails CUDA 11.7 test
Pull Request resolved: https://github.com/pytorch/pytorch/pull/86344
Approved by: https://github.com/atalman, https://github.com/malfet