Fix missing newline in compiled from source range highlihgt (#25802)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/25802

Test script

```
import torch

def foo(x, y):
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    return x

scripted = torch.jit.script(foo)
scripted.save('foo.zip')

loaded = torch.jit.load('foo.zip')
loaded(torch.rand(3, 4), torch.rand(4, 5))
```

Before this change
```
RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1
The above operation failed in interpreter, with the following stack trace:
at code/__torch__.py:7:9
op_version_set = 1
class PlaceholderModule(Module):
  __parameters__ = []
  def forward(self: __torch__.PlaceholderModule,
    x: Tensor,
    y: Tensor) -> Tensor:
    x0 = torch.add(x, y, alpha=1)
         ~~~~~~~~~ <--- HERE
    x1 = torch.add(x0, y, alpha=1)
    x2 = torch.add(x1, y, alpha=1)
    x3 = torch.add(x2, y, alpha=1)
    x4 = torch.add(x3, y, alpha=1)
    x5 = torch.add(x4, y, alpha=1)
    x6 = torch.add(x5, y, alpha=1)
    x7 = torch.add(x6, y, alpha=1)
    x8 = torch.add(x7, y, alpha=1)
    x9 = torch.add(x8, y, alpha=1)Compiled from code at /home/jamesreed/print_test.py:5:8
def foo(x, y):
    x = x + y
        ~~~~~ <--- HERE
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
```

After this change
```
RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1
The above operation failed in interpreter, with the following stack trace:
at code/__torch__.py:7:9
op_version_set = 1
class PlaceholderModule(Module):
  __parameters__ = []
  def forward(self: __torch__.PlaceholderModule,
    x: Tensor,
    y: Tensor) -> Tensor:
    x0 = torch.add(x, y, alpha=1)
         ~~~~~~~~~ <--- HERE
    x1 = torch.add(x0, y, alpha=1)
    x2 = torch.add(x1, y, alpha=1)
    x3 = torch.add(x2, y, alpha=1)
    x4 = torch.add(x3, y, alpha=1)
    x5 = torch.add(x4, y, alpha=1)
    x6 = torch.add(x5, y, alpha=1)
    x7 = torch.add(x6, y, alpha=1)
    x8 = torch.add(x7, y, alpha=1)
    x9 = torch.add(x8, y, alpha=1)
Compiled from code at /home/jamesreed/print_test.py:5:8
def foo(x, y):
    x = x + y
        ~~~~~ <--- HERE
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
    x = x + y
```

Test Plan: Imported from OSS

Differential Revision: D17250599

Pulled By: jamesr66a

fbshipit-source-id: 56266dcbf2c2287dc8ced7b9463ed42ef5f1167c